//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mahasiswa.java
//  @ Date : 3/20/2013
//  @ Author : 
//
//




public class Mahasiswa extends Manusia {
	protected Object NPM;
	protected Object Status;
}
