//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Manusia.java
//  @ Date : 3/20/2013
//  @ Author : 
//
//




public class Manusia {
	protected Object NIK;
	protected Object nama;
	protected Object JK;
        private String al;
	public void set_manusia_detail() {
	
	}
	
	protected void cetak_manusia() {
	
	}
        
        private void coba_manusia() {
	
	}
}
