//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pegawai.java
//  @ Date : 3/20/2013
//  @ Author : 
//
//




public class Pegawai extends Manusia {
	protected int NIP;
	protected String Status;
	protected Object Jabatan;
	protected Object Gaji;
}
