//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sarjana.java
//  @ Date : 3/20/2013
//  @ Author : 
//
//




public class Sarjana extends Mahasiswa {
	public void uk()
	{
	}
}
